WEX Salesforce project/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This is the project object that will store the project information. It is composed of a milestones and is only completed when all of them are completed.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <description>Project milestones, composed of to-do activities.</description>
    <label>Project Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/fields/Percentage_of_Completion__c.field-meta.xml
<CustomField>
    <fullName>Percentage_of_Completion__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percentage of Completion</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_and_Milestones_Status</valueSetName>
    </valueSet>
</CustomField>

WEX Salesforce project/force-app/main/default/globalValueSets/Project_and_Milestones_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <description>Shared values for field Status for Project and Project Milestone Objects</description>
    <masterLabel>Project and Milestones Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

WEX Salesforce project/force-app/main/default/classes/ProjectMilestoneTriggerHandler.cls
public with sharing class ProjectMilestoneTriggerHandler {
    
    public static void handleBeforeUpdate(Map<Id,Project_Milestone__c> newMap, Map<Id,Project_Milestone__c> oldMap){
        updateMilestoneFields(newMap.values());
    }

    public static void handleBeforeInsert(List<Project_Milestone__c> newList){
        updateMilestoneFields(newList);
    }

    public static void handleAfterUpdate(Map<Id,Project_Milestone__c> newMap, Map<Id,Project_Milestone__c> oldMap){
        List<Id> projectIdList = extractProjectIdsFromMilestones(newMap, oldMap);
        ProjectMilestoneTriggerHandlerUtils.updateProjectCompletion(projectIdList);
    }

    public static void handleAfterInsert(Map<Id,Project_Milestone__c> newMap){
        List<Id> projectIdList = extractProjectIdsFromMilestones(newMap, null);
        ProjectMilestoneTriggerHandlerUtils.updateProjectCompletion(projectIdList);
    }

    public static void handleAfterDelete(Map<Id,Project_Milestone__c> oldMap){
        List<Id> projectIdList = extractProjectIdsFromMilestones(oldMap, null);
        ProjectMilestoneTriggerHandlerUtils.updateProjectCompletion(projectIdList);
    }

    public static void handleAfterUndelete(Map<Id,Project_Milestone__c> newMap){
        List<Id> projectIdList = extractProjectIdsFromMilestones(newMap, null);
        ProjectMilestoneTriggerHandlerUtils.updateProjectCompletion(projectIdList);
    }

    public static void updateMilestoneFields(List<Project_Milestone__c> milestoneList){
        for(Project_Milestone__c milestone : milestoneList){
            milestone.Status__c = milestone.Percentage_of_Completion__c >= 100 ? 'Complete' 
                    : milestone.Percentage_of_Completion__c > 0 ? 'In Progress'
                    : 'Not Started';
        }
    }

    public static List<Id> extractProjectIdsFromMilestones(Map<Id,Project_Milestone__c> milestoneMap, Map<Id,Project_Milestone__c> comparisonMap){
        List<Id> projectIdList = new List<Id>();
        for(Project_Milestone__c milestone : milestoneMap.values()){
            if(comparisonMap == null || milestone.Status__c != comparisonMap.get(milestone.Id).Status__c){
                projectIdList.add(milestone.Project__c);
            }
        }
        return projectIdList;
    }
}