WEX Salesforce project/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This is the project object that will store the project information. It is composed of a milestones and is only completed when all of them are completed.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <description>Project milestones, composed of to-do activities.</description>
    <label>Project Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

WEX Salesforce project/force-app/main/default/classes/ProjectCreatorAssistantController.cls
public with sharing class ProjectCreatorAssistantController {
    @AuraEnabled
    public static void saveRecords(String data) {
        Map<String, Object> parsedData = (Map<String, Object>) JSON.deserializeUntyped(data);
        String projectName = (String) parsedData.get('projectName');
        List<Object> milestones = (List<Object>) parsedData.get('milestones');
        
        Project__c project = new Project__c(Name = projectName);

        insert project;
        List<Project_Milestone__c> milestonesList = new List<Project_Milestone__c>();
        List<List<Task>> taskListList = new List<List<Task>>();
        Integer auxIndex = 0;

        for (Object milestoneObj : milestones) {
            Map<String, Object> milestoneMap = (Map<String, Object>) milestoneObj;
            Project_Milestone__c milestone = new Project_Milestone__c(
                Name = (String) milestoneMap.get('name'),
                Project__c = project.Id
            );

            milestonesList.add(milestone);
            List<Task> auxTaskList = new List<Task>();

            List<Object> tasks = (List<Object>) milestoneMap.get('tasks');
            for (Object taskObj : tasks) {
                Map<String, Object> taskMap = (Map<String, Object>) taskObj;
                Task task = new Task(
                    Subject = (String) taskMap.get('name'),
                    WhatId = milestone.Id
                );
                auxTaskList.add(task);
            }
            taskListList.add(auxTaskList);
        }

        if(!milestonesList.isEmpty()) insert milestonesList;

        List<Task> taskToInsertList = new List<Task>();
        
        for(Integer index = 0; index < taskListList.size(); index++){
            for(Task task : taskListList[index]){
                task.WhatId = milestonesList[index].Id;
                taskToInsertList.add(task);
            }
        }

        if(!taskToInsertList.isEmpty()) insert taskToInsertList;
    }
}