WEX Salesforce project/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This is the project object that will store the project information. It is composed of a milestones and is only completed when all of them are completed.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <description>Project milestones, composed of to-do activities.</description>
    <label>Project Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/fields/Percentage_of_Completion__c.field-meta.xml
<CustomField>
    <fullName>Percentage_of_Completion__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percentage of Completion</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

WEX Salesforce project/force-app/main/default/objects/Project_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_and_Milestones_Status</valueSetName>
    </valueSet>
</CustomField>

WEX Salesforce project/force-app/main/default/globalValueSets/Project_and_Milestones_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <description>Shared values for field Status for Project and Project Milestone Objects</description>
    <masterLabel>Project and Milestones Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

WEX Salesforce project/force-app/main/default/classes/ProjectMilestoneTriggerHandlerUtils.cls
public with sharing class ProjectMilestoneTriggerHandlerUtils {
    
    public static void updateProjectCompletion(List<Id> projectIdsList){

        List<Project__c> projectUpdateList = new List<Project__c>();
        Map<Id,Integer> mapProjectIdToCompleteMilestones = new Map<Id,Integer>();
        Map<Id,Integer> mapProjectIdToTotalMilestoneNumber = new Map<Id,Integer>();

        for(Project_Milestone__c milestone : [SELECT Id, Status__c, Project__c 
                                            FROM Project_Milestone__c
                                            WHERE Project__c IN: projectIdsList]){
            if(!mapProjectIdToTotalMilestoneNumber.containsKey(milestone.Project__c)){
                mapProjectIdToCompleteMilestones.put(milestone.Project__c, 0);
                mapProjectIdToTotalMilestoneNumber.put(milestone.Project__c, 0);
            }

            mapProjectIdToTotalMilestoneNumber.put(milestone.Project__c, 
                    mapProjectIdToTotalMilestoneNumber.get(milestone.Project__c) + 1);
            if(milestone.Status__c == 'Complete'){
                mapProjectIdToCompleteMilestones.put(milestone.Project__c, 
                        mapProjectIdToCompleteMilestones.get(milestone.Project__c) + 1);
            }
        }

        Project__c auxProject = new Project__c();
        for(Id projectId : projectIdsList){
            auxProject.Id = projectId;
            auxProject.Percentage_of_Completion__c = mapProjectIdToTotalMilestoneNumber.containsKey(projectId)
                    ? mapProjectIdToCompleteMilestones.get(projectId) * 100 / mapProjectIdToTotalMilestoneNumber.get(projectId) 
                    : 0;
            auxProject.Status__c = auxProject.Percentage_of_Completion__c >= 100 ? 'Complete' 
                    : auxProject.Percentage_of_Completion__c > 0 ? 'In Progress'
                    : 'Not Started';
            
            projectUpdateList.add(auxProject);
        }

        if(!projectUpdateList.isEmpty()){
            update projectUpdateList;
        }
    }
}